name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-jiri-rs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jiri-rs
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -v
      - name: Run tests
        run: cargo test -v
  
  build-jiri-wasm-www:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jiri-wasm
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build with wasm-pack
      run: wasm-pack build
    - name: Build www
      working-directory: ./jiri-wasm/www
      run: npm i && npm run build

  build-jiri-wasm-egui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jiri-wasm/egui
    steps:
    - uses: actions/checkout@v3
    - name: Install trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | sudo tar -xzf- -C /usr/local/bin
    - name: Install target wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
    - name: Build egui
      run: trunk build

  build-jiri-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jiri-web
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: yarn install && yarn build
